<?php
/**
 * Copyright (c) 2016 TechDivision GmbH
 * All rights reserved
 *
 * This product includes proprietary software developed at TechDivision GmbH, Germany
 * For more information see http://www.techdivision.com/
 *
 * To obtain a valid license for using this software please contact us at
 * license@techdivision.com
 */

/**
 * @category   Magenerds
 * @package    Magenerds_GermanLaw
 * @subpackage view
 * @author     Florian Sydekum <f.sydekum@techdivision.com>
 * @copyright  Copyright (c) 2016 TechDivision GmbH (http://www.techdivision.com)
 * @link       http://www.techdivision.com/
 */

/**
 * @var $block \Magenerds\GermanLaw\Block\AfterPrice
 */
?>
<?php if (!$block->isEnabled()) return; ?>

<?php if ($block->isAsterisk()): ?>
    <span>(*)</span>
<?php else: ?>
    <span class="tax-details">
        <?php echo $block->getTaxText() ?>
    </span>
<?php endif; ?>
